/**
 * Parser/serializer pra js/plugins.js do projeto MZ.
 *
 * Formato:
 *   // Generated by RPG Maker.
 *   // Do not edit this file directly.
 *   var $plugins =
 *   [
 *   {"name":"PluginA","status":true,"description":"...","parameters":{...}},
 *   {"name":"PluginB","status":false,"description":"","parameters":{}}
 *   ];
 *
 * Extraímos o array $plugins usando regex tolerante a whitespace; serializa de
 * volta em formato canônico.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

import type { Config } from '../config.js';
import { mzError } from '../utils/errors.js';
import { safeWrite } from './safe-writer.js';
import { detectEditorLock } from './lock-detect.js';
import { logger } from '../utils/logger.js';
import { bumpSystemVersionId } from './version-bump.js';
import { createSnapshot, pruneSnapshots } from './backup.js';

export interface PluginRegistryEntry {
  name: string;
  status: boolean;
  description: string;
  parameters: Record<string, unknown>;
}

const HEADER = `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n`;

export async function loadPluginsJs(config: Config): Promise<PluginRegistryEntry[]> {
  const filePath = path.join(config.project.path, 'js', 'plugins.js');
  let raw: string;
  try {
    raw = await fs.readFile(filePath, 'utf-8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      logger.debug('js/plugins.js não existe, retornando array vazio.');
      return [];
    }
    throw err;
  }

  // Extrai o array entre `[ ... ];`
  const match = /\$plugins\s*=\s*(\[[\s\S]*?\])\s*;/m.exec(raw);
  if (!match) {
    throw mzError('plugin_invalid', `Não consegui parsear js/plugins.js. Formato esperado: var $plugins = [...]`);
  }
  try {
    const arr = JSON.parse(match[1]!);
    if (!Array.isArray(arr)) throw new Error('not array');
    return arr.map((p) => ({
      name: String(p.name ?? ''),
      status: !!p.status,
      description: String(p.description ?? ''),
      parameters: (p.parameters as Record<string, unknown>) ?? {},
    }));
  } catch (err) {
    throw mzError('plugin_invalid', `JSON inválido em js/plugins.js: ${(err as Error).message}`);
  }
}

export async function savePluginsJs(
  config: Config,
  entries: PluginRegistryEntry[],
  opts: { destructive?: boolean; snapshotLabel?: string } = {},
): Promise<void> {
  // Lock check
  const lock = await detectEditorLock();
  if (lock === 'locked' && config.editor.onLock === 'block') {
    throw mzError(
      'editor_locked',
      'Editor MZ está aberto. Feche-o antes (config editor.onLock=block).',
    );
  } else if (lock === 'locked' && config.editor.onLock === 'warn') {
    logger.warn('Editor MZ parece aberto — escrita prosseguindo com versionId bump.');
  }

  if (opts.destructive && config.project.autoBackup) {
    await createSnapshot(
      config.project.path,
      config.project.backupDir,
      opts.snapshotLabel ?? 'before-plugins-js-write',
    );
    await pruneSnapshots(
      config.project.path,
      config.project.backupDir,
      config.project.backupRetention,
    );
  }

  const lines = entries.map((p) =>
    JSON.stringify({
      name: p.name,
      status: p.status,
      description: p.description,
      parameters: p.parameters,
    }),
  );
  const body = `[\n${lines.join(',\n')}\n];\n`;
  const content = HEADER + body;

  const filePath = path.join(config.project.path, 'js', 'plugins.js');
  await safeWrite(filePath, content);

  try {
    await bumpSystemVersionId(config.project.path);
  } catch (err) {
    logger.warn(`Falha bumpando versionId após escrever plugins.js: ${(err as Error).message}`);
  }
}
